### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.zh-tw#3]
English:
Direct students to
https://aka.ms/az204labs

Current Translation:
引導學生 至https://aka.ms/az204labs

Suggested Translation:
引導學生至https://aka.ms/az204labs

Description:
Space issue

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
Bold issue, I can't fix the issue.
